name: Generate Weekly AI-Tips Post

on:
  schedule:
    - cron: '0 9 * * FRI'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate new post
        run: python scripts/generate_post.py
      - name: Commit and push new post
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/
          git commit -m "Automatiskt genererat inlägg $(date +'%Y-%m-%d')"
          git push